[project]
name = "hammymapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "e3x>=1.0.2",
    "numpy>=2.3.5",
    "pytest>=9.0.1",
]
